sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/ubuntu
  - secure: d3Ljm3Iirl+jRAvdtSplMMEmHY546Kb3EqOfI+JkKFfBPr1BXrCfYQkT0Gd+r+HS4EyiOBVZzSwznbyc4IwidGwAlCK5qCQwMCyjzlwdRA+kdUr5bPneFwHFpYcvqupCcjYOmkuP/TMC85w+k756ZyYM1h8mkwzHOTOFEcAqbmW9LOLQ4GNBMZNFQhQULBDL3V4hgRL72dCXUH1GIoO3IHi9mQ45fkPqkKX3MdU7nH9FdTkqPPD6ECOpTIk9TEFSMpIxCBqGl8a9upyTFDXLjSLB2p+iYbi86iB7+IlQtYtSBkTQKtCdtPOlpYumnUXf5wtwBcnxLER8DhppYBbwoP4jsjJZLqtYmZysCdwB5oO5BgMRsUNDXnS7ZITwzUOW/G9HyJzsLaf2jqsy/TGHGLQ9DdJiTYjjjw37h0gTUXeTfP08dj0Wvu+w0Vewc1F28rybjk/OIGpxAjojWbFGRhoTYthbcSVVGC48DAJ1KMyl3RcgG6oonEFhcIaqwAhyzVbmbeTRegz79s5+Gn1ooh/nT0MGnOPwaF3XPBcsx0xi7UuRvHoHzNENvkSf8UyXl/smHyhc7DQyEfqtahZnaEL0yIXobuzJU01aowrK59hBefR4WL84Nc/cOlsQEgv5yaJuXoqzXaESOoe+TTq+seMnIoQ9psV6Imhyk7CgKJA=
  - secure: V3plz73Ae5gJN5LT2YdxQmogdN1nFfMpA1cnyvl25iN0T21WxBwn4JLwXFwVfFOmiaDMicDK6Wc3M+45pi2bJrWyryUBdGQ+jEDLRv+oS6BWhLfedgY7BuTHlIQN2Mck04TSt5EdrR9uiJ6pH6tubLa9QxsWH3aTWGnyBPxtiiFImaEKDkXzbTAZ+QSbeZ94vbyfwy9zHHZpEKFGHjr02jdx6o00KAUZHj2mZeeE9/iTV4cDVXBpYpgnbNvx5gsI49p/8s9fQgNL/QtRXXuQGdddx99zIKtrXPd3KRkhCNCQkJJ3ZAWxP5hGY8BElJjZifY5+TwTsNIRR1Sqw0D9tiWWjhloDse6HvfdWjo9HXkJ6gOkvfxO4vu5nc+jthkkHpqx1t6RTzMoVItd9Gax8HHQJ/fbs7QLP8xxxmRdQsKJh9R8hVMivI+Zr1iXeSlG94dWgjAw032BdpzHMiM1PUjNLAzk/KW6sBoPe9/ze+CBwsw2+9gk7R5JredwiVORkiJNi+WsyTyrat44v0z1I6apPpaW3+5mDhf0GydDyl2Ats948htEYZeJ0GwzJSBlL1RaakxbhTITLLZLMwhO31paISlm9E7g/HVEQ6HqY17zZCS2BTAVLBILIpccA2AuAlyKrSg8wM7pu7v/rFvAFAbKfCUqoTHoRMbgO+PdrYc=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "bionic"; else echo $TRAVIS_BRANCH; fi`
- export REPO=dairyd/ubuntu
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
