sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/ubuntu
  - secure: hidVppB1E9MhQxQIrGfgbcxMB/aqCG0mGQwUGHDxT/q5UW6hJ2Ht4sLRqrNQDdVz955MwlvBEKUw84anYIZct73caoM/V7dGvnyHKdtbofjhsXPtBhpAJFyxArgw8gHqRoP4YY8vcJYnhMiwDWBf3ti19rF6sObqZ5q8bSt2vnvVq+0ccwhyIgrTRUTngtR0bHYQsKwJxGLJPIfklq2LifkI1BG2sTauLDp3CrHygtticSxLn+GCY5yhZgZEanAcqkEKR95kcag1GTDBFHgfOhfWgTrkpo+fUU4p+SC+ipMotaosmY/wOyfcD9Ks5NLrCM+OtUG/bYs440ysMmmDErUbE3Rr+lKGugz2Qrxh46hRRBiXD/gMUDaspi93sJ6Zo/LjuNtkn2C8Lbp5sDdVWyqWRRG7FZA4zYmfcdaxuPWxHZB+0tmN4+CggKpkbWyl8fhUpp4u+fnyHPMkeLmsOiDfNvSk3st/TnusSCLrzpHPkxJi3OTxIsZUisPaAvgJ/bcr4txI1MfDzZlgTEsiyra5flua6uouYmUWurRcE5hcdPGD560T9y0LrBxKmE2/Ur/w/U+cfeSSmXf5GIYlYRPf1uUEv39Bs1klKRFz+SHR5yW3Sij/4+6zK3QvXUOk1VgNzUDxE3xZDruIlg1aHFVX9+kXCUHGoDlYexUuYM4=
  - secure: Fcez8bDSYOFa4niHrPLb94/kI92GN6lNPMZ5GB4H9GyY1eVZRfCCMEpih3epHCxwha/tbUYNifPef190zELmBoZlvKhIVRaeBZr8vwoahSl7tmr/QgSqSssrBf3dVuNmm941xIDFmtCMa2gPUuzR6jOTzDBCLgF0jEpw22E6GKW17kOcLT+SlV40OWahj1opVUu+7SXBv4nkVNyNwBQyCn/k0MKTFmEftj99hbHX61o+zOvLiGj9QLQDHYaGN3+OU2J06wkc+zJpY6y0BTlfKzPIJvL2IGmWWqUEl07lU3Nsw7Mh0Btwh4KSXHh6Dg4VT/o0Pg/flNJ3dzELz/5QIiw8XoeAgewYK5gG8cuS9kDJ8Fe09sH0BJeq2ic9EijcgcmsIXvC9wJkgB+wIChuptOAINqa9dzCWNtgBY+zklJpZAQo7JuFkjqdiiVsy/+9BsKGLCJGsleAiOKjpU2bPDDgxp3vpksTZigRaDpuKwwD1Uv8HS4F7c/2ANjl9iNoToxOOVmOl1dZ/51cR5VHlaqwWZW8OEsVG5F0F/NE+anlTWRKUD3goCIms3dcwyvgm021qx1z8mr06p5/dIxWtHsgRVPkRfZD+rP+dg3sofJv7vVy/2UprJAyMVXr5BhP6UpNHBCGvNKpQ7PGoh4bIYWj3IZDNwJSw3s2mNFGjIM=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "bionic"; else echo $TRAVIS_BRANCH; fi`
- export REPO=dairyd/ubuntu
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
