sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/ubuntu
  - secure: t2nbQ5cqBcaA86vbqC01pwwsbeZIswk7Zxjckmnm6M2yu6a5IWWOSwqcEQ17Qm5jLWHT/2ifZ00ZUrXIIcRNF589twLt+5P3+fIa9GFlq6pLOAhEG+2xDOFQ2D+QHppkPFRdAfx9M9CZOYntEbS2JdD1Sdr5WhoxYEE0/YDUsGWshEbsGMkq3WP+Ei2Ii5UibKPpgUP8pakkJbd3TG5RB0O8MxNFt7A+nIPWa3CoqCG5cMxMDBz04SIqigMOlO2wRHUJcAVd0fJqzDXa4F86nybqoheenPcFoXjnoxU29A7X7OFRkeuCrLR02WWKKRJ4CBd1tvci/wCo3Gvuu26WciKqqZfBNscnzTAPWNa0fY7vRK3IenVjmfp2phIGaew0xhQuRq1p8fX5WDvG85Gcpj8OA20D8uspddk+NJZsWIN7y6F9qLt/Q7bNYUJtWRsnlLuCdAiQrDGntOlMUGViPlQX+pCA3nEo85mm+zVgis7nI+1WruLDJBAGG+tsov4EvJNcFLCck3EbaA1G8Jfh3v4Tjltey3ewwu7/UdypBSGAs+fzZt3Sgc7PXc3y7BVKuj4i7B/mRjld/QpjrKRsBzsZjcvoU9HGB0jWx89bgudpoMrXq5I49PfJWdKRXBUUcx1R3Rd7HtZaZqxPwytdvdratJh6pSbI3oP3URXqaEE=
  - secure: BMO5N2Q/qL8HWCZSBwPEaVfQ4X5lw5fJlQuRSEh0VxIfqCV73Io8KBheSV4DFXACgdt8ZkspAv1o3j5VIb5Lq+NFGfQ5wFF9MSApd3wHIMlgh/UKQgeuX2EO82npGWEE4O66Ze6bkc3dmF57j6hG+w/BUGjT+vVZUd8la13FlyzlbwaWdKFIt/7Hjyd8YJGiSVvnTO5LIv0YT9msJurXqwZgn9Tg2sDDoJ3kXpohFP9CWp3cO6Y+ncFtA9pJoi8eD2DAKYvynObKnlztumUxZ8apbiZKVZcdjQ4/XZ+Q2etVjiMAGBZOvOmKn9+5lQ2yFaeb0hoEvBIe5gW8/Ig7dFtEUiKZEfWoBifuJEsPhBrI1iMTcCgWC/xkqbcSy1EzxKo5L1RtwKYEi9me+1AIBiuy++nzQ4n6GNskzKrfZq5Vllbn4QNqVs0/bANNRRJkUC2XjeyFNBjDMg1wIcJ4rZ8NxwEYm4I+Lgd72J2ivTjXFds4dePnDgLnmvVOjC+89YNW6gWWqG/7C2Sk4rOZyPbq9VY9YStEtlQEo+VcXtiGkmmi/RgmJCJj8LvN7XhmIbrvpkcwImNomwr3NrNmGNq+eog6/CgZrqcJO4gFmR7AQvTUL0ca324AHJZlZGMSrctDVmn2uKhZYinHzaTQQUtImMn+nccnm0Ren92fBZg=

script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "bionic"; else echo $TRAVIS_BRANCH; fi`
- export REPO=dairyd/ubuntu
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
