sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/ubuntu
  - secure: b843gTjFUc8oC/VsP3EyxYYBgeRzTHMJIp7iGrhZLt711OKBAbV53kP9pDOdoUY+A7oPebC0ccYwabKJaHEOOF8M2uz1P/imXGYlbReZf4PvOeaAMapkh4MuhFpRi5qNqXqDCxc6cvNnj+auteppb6TIaSVjC6iaFS/HjsgDTRdSOuP3XCjGmHw7UUjxgRRr+c923ZIAA96xNcazUtvEp3G+Fjn9THCrdW6rTPvA24ZCU2njDPz1T4okvHa6yjsMSda+qf/TEGq58tnPFdH1OspJ5whc9uBbVqQa8JljPiNUfsg+QrQFNnZQak8gjGMy6D7lgWK8dTU525DxvXGCMtvhPvX12CSzcWhyhU+aCPcvZksk4yW3P97ZKkFZhb/4lSQN+0qisvBuxB61U/shMP/Ko50ZUmBpJIFX7Q4F+DMT2sWBOhGBDutYtxwACc06w1oLLB7heYDd6SuBni28lhWhG7Acr2s69qpgjYzz9qypEGWm1WtwVIu7DEYs0J6VqWwPoAQzqZHkvcYcfa0bmk++R4dIe9FYkNX5Eh9NTzQoKlg4fyimqd8bOXU5hxd2CP8w1g6D6sHAcPgF8WM/SAFfzZjPyNBK9mADocAjwvkI8eEvLsHiyhom87aVyjHjFIGhKElblsZDzgLIvWGCHZmN9B6ZMYGJ4MPMEjCA6Bg=
  - secure: XkvD3zaE5ReH0I4n5z9oQv+RKUgKvnsN5GtKJZJWTX4L2UHRyy7rOWX79/tEL6AwV3bpW0gDPc+ua9gjTXw8VEoRMbp9SuylEWPPzatq8JG5ifFnpU7myvhVPCvvyFQrjSxGsbWyI2gsRIVSSd/DpZgX4bO5Hl5Tnfi9P0ew06VbdX0vifep1ypqm1S5gWPGhY3nuctBk9qB1Pa0ocHxZesgNdPMTRpo6I8T69Tst5Fk/7Mxva5W8VzwOChBhMvlm0sNA83A1ixjCRhfC/uBCFZ2aYceek9/VTEeSbLDVNJouS5lCAKvNA+dTlDYDFXxJlmG34VJZbLANOKXRzTYgWhQdWjUJfozH+WLGMMgguRwHrcqhnwSsc54dHvzYLGjZEd641SE6c9ivOGVjvHKiv4IPV5qFegdInFtNEju8HaoVlmFWgrDVB/jOcWCZddP/zmPX+ms8HLEWg87DiIq2XAJcRVcLY5kGxqv+U4WC+JSeeNBmD8k9jneQcAl44aq/YenU0vGOo5NLoQr9hY6tsOq3bE3crIMrMCjURpuQtauY2JKFn10nKr6sX7ibMS1sdtw2N61sa/wh9QS0y+pJOdQLhzGTC2CYbZ4HbviUhORzwQv+2GjUtz3dZlWgoo7FxZN6Ya5c6KpoXVsyYdsUbMDKqa/dq9j6FGBOw17+bk=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "bionic"; else echo $TRAVIS_BRANCH; fi`
- export REPO=dairyd/ubuntu
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
